### ISSUE TITLE
another erro with pip install --no-cache-dir --ignore-installed -r requires.dev.txt

### ISSUE THREAD

**Issue by baditaflorin** [geometalab/OSM-Crosswalk-Detection#76]
Fixed the latest reported error by using sudo apt-get install python-dev

But now i get a new error
 pip install --no-cache-dir --ignore-installed -r requires.dev.txt
Collecting autopep8 (from -r requires.dev.txt (line 1))
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading autopep8-1.2.4-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 68kB/s 
Collecting click (from -r requires.dev.txt (line 2))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 59.8MB/s 
Collecting coverage (from -r requires.dev.txt (line 3))
  Downloading coverage-4.1.tar.gz (370kB)
    100% |████████████████████████████████| 378kB 39.5MB/s 
Collecting django-environ (from -r requires.dev.txt (line 4))
  Downloading django-environ-0.4.0.tar.gz
Collecting fake-useragent (from -r requires.dev.txt (line 5))
  Downloading fake-useragent-0.0.8.tar.gz
Collecting flake8 (from -r requires.dev.txt (line 6))
  Downloading flake8-2.5.4-py2.py3-none-any.whl
Collecting geopy (from -r requires.dev.txt (line 7))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 47.9MB/s 
Collecting h5py (from -r requires.dev.txt (line 8))
  Downloading h5py-2.6.0.tar.gz (245kB)
    100% |████████████████████████████████| 245kB 58.4MB/s 
^COperation cancelled by user
(.venv27crosswalks) florinb@florinb-VirtualBox:~/OSM-Crosswalk-Detection$ pip install --no-cache-dir --ignore-installed -r requires.dev.txt
Collecting autopep8 (from -r requires.dev.txt (line 1))
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading autopep8-1.2.4-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.3MB/s 
Collecting click (from -r requires.dev.txt (line 2))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 2.7MB/s 
Collecting coverage (from -r requires.dev.txt (line 3))
  Downloading coverage-4.1.tar.gz (370kB)
    100% |████████████████████████████████| 378kB 41.0MB/s 
Collecting django-environ (from -r requires.dev.txt (line 4))
  Downloading django-environ-0.4.0.tar.gz
Collecting fake-useragent (from -r requires.dev.txt (line 5))
  Downloading fake-useragent-0.0.8.tar.gz
Collecting flake8 (from -r requires.dev.txt (line 6))
  Downloading flake8-2.5.4-py2.py3-none-any.whl
Collecting geopy (from -r requires.dev.txt (line 7))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 53.5MB/s 
Collecting h5py (from -r requires.dev.txt (line 8))
  Downloading h5py-2.6.0.tar.gz (245kB)
    100% |████████████████████████████████| 245kB 50.0MB/s 
Collecting httplib2 (from -r requires.dev.txt (line 9))
  Downloading httplib2-0.9.2.zip (210kB)
    100% |████████████████████████████████| 215kB 58.0MB/s 
Collecting Keras==1.0.1 (from -r requires.dev.txt (line 10))
  Downloading Keras-1.0.1.tar.gz (109kB)
    100% |████████████████████████████████| 112kB 31.0MB/s 
Collecting nose (from -r requires.dev.txt (line 11))
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 44.4MB/s 
Collecting numpy (from -r requires.dev.txt (line 12))
  Downloading numpy-1.11.0-cp27-cp27mu-manylinux1_x86_64.whl (15.3MB)
    100% |████████████████████████████████| 15.3MB 53.6MB/s 
Collecting Pillow (from -r requires.dev.txt (line 13))
  Downloading Pillow-3.2.0.zip (10.5MB)
    100% |████████████████████████████████| 10.5MB 51kB/s 
Collecting PyYAML (from -r requires.dev.txt (line 14))
  Downloading PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 44.7MB/s 
Collecting redis (from -r requires.dev.txt (line 15))
  Downloading redis-2.10.5-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 32.6MB/s 
Collecting rq (from -r requires.dev.txt (line 16))
  Downloading rq-0.6.0-py2.py3-none-any.whl (48kB)
    100% |████████████████████████████████| 51kB 52.6MB/s 
Collecting scipy (from -r requires.dev.txt (line 17))
  Downloading scipy-0.17.1-cp27-cp27mu-manylinux1_x86_64.whl (39.5MB)
    100% |████████████████████████████████| 39.5MB 4.0MB/s 
Collecting six (from -r requires.dev.txt (line 18))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting Theano==0.8.2 (from -r requires.dev.txt (line 19))
  Downloading Theano-0.8.2.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 32.7MB/s 
Collecting pep8>=1.5.7 (from autopep8->-r requires.dev.txt (line 1))
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 53.9MB/s 
Collecting django (from django-environ->-r requires.dev.txt (line 4))
  Downloading Django-1.9.6-py2.py3-none-any.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 16.6MB/s 
Collecting pyflakes<1.1,>=0.8.1 (from flake8->-r requires.dev.txt (line 6))
  Downloading pyflakes-1.0.0-py2.py3-none-any.whl (152kB)
    100% |████████████████████████████████| 153kB 10.2MB/s 
Collecting mccabe<0.5,>=0.2.1 (from flake8->-r requires.dev.txt (line 6))
  Downloading mccabe-0.4.0-py2.py3-none-any.whl
Installing collected packages: pep8, autopep8, click, coverage, django, six, django-environ, fake-useragent, pyflakes, mccabe, flake8, geopy, numpy, h5py, httplib2, scipy, Theano, PyYAML, Keras, nose, Pillow, redis, rq
  Running setup.py install for click ... done
  Running setup.py install for coverage ... done
  Running setup.py install for django-environ ... done
  Running setup.py install for fake-useragent ... done
  Running setup.py install for h5py ... error
    Complete output from command /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-U8YZvA/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1FLFQJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/include/site/python2.7/h5py:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/h5py
    copying h5py/version.py -> build/lib.linux-x86_64-2.7/h5py
    copying h5py/__init__.py -> build/lib.linux-x86_64-2.7/h5py
    copying h5py/highlevel.py -> build/lib.linux-x86_64-2.7/h5py
    copying h5py/ipy_completer.py -> build/lib.linux-x86_64-2.7/h5py
    creating build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/selections.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/dims.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/files.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/group.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/filters.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    copying h5py/_hl/base.py -> build/lib.linux-x86_64-2.7/h5py/_hl
    creating build/lib.linux-x86_64-2.7/h5py/tests
    copying h5py/tests/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests
    copying h5py/tests/common.py -> build/lib.linux-x86_64-2.7/h5py/tests
    creating build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/common.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
    creating build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_threads.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_datatype.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_dataset_swmr.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    copying h5py/tests/hl/test_attribute_create.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
    running build_ext
    Autodetection skipped [libhdf5.so: cannot open shared object file: No such file or directory]
    ********************************************************************************
                           Summary of the h5py configuration
    
        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: False
    
    ********************************************************************************
    Executing api_gen rebuild of defs
    Executing cythonize()
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/defs.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/_errors.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/_objects.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/_proxy.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5fd.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5z.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5i.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5r.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/utils.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/_conv.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5t.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5s.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5p.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5d.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5a.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5f.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5g.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5l.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5o.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5ds.pyx because it changed.
    Compiling /tmp/pip-build-U8YZvA/h5py/h5py/h5ac.pyx because it changed.
    [ 1/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/_conv.pyx
    [ 2/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/_errors.pyx
    [ 3/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/_objects.pyx
    [ 4/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/_proxy.pyx
    [ 5/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/defs.pyx
    [ 6/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5.pyx
    [ 7/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5a.pyx
    [ 8/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5ac.pyx
    [ 9/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5d.pyx
    [10/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5ds.pyx
    [11/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5f.pyx
    [12/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5fd.pyx
    [13/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5g.pyx
    [14/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5i.pyx
    [15/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5l.pyx
    [16/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5o.pyx
    [17/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5p.pyx
    [18/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5r.pyx
    [19/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5s.pyx
    [20/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5t.pyx
    [21/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/h5z.pyx
    [22/22] Cythonizing /tmp/pip-build-U8YZvA/h5py/h5py/utils.pyx
    building 'h5py.defs' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/tmp
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-U8YZvA
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-U8YZvA/h5py
    creating build/temp.linux-x86_64-2.7/tmp/pip-build-U8YZvA/h5py/h5py
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DH5_USE_16_API -I/tmp/pip-build-U8YZvA/h5py/lzf -I/opt/local/include -I/usr/local/include -I/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/pip-build-U8YZvA/h5py/h5py/defs.c -o build/temp.linux-x86_64-2.7/tmp/pip-build-U8YZvA/h5py/h5py/defs.o
    In file included from /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                     from /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from /tmp/pip-build-U8YZvA/h5py/h5py/api_compat.h:26,
                     from /tmp/pip-build-U8YZvA/h5py/h5py/defs.c:303:
    /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /tmp/pip-build-U8YZvA/h5py/h5py/defs.c:303:0:
    /tmp/pip-build-U8YZvA/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory
     #include "hdf5.h"
                      ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-U8YZvA/h5py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1FLFQJ-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/florinb/OSM-Crosswalk-Detection/.venv27crosswalks/include/site/python2.7/h5py" failed with error code 1 in /tmp/pip-build-U8YZvA/h5py/

**Comment by marcelhuberfoo** [comment]
Similar to #75. See 'install locally' section or browse the Dockerfiles to find prerequisite packages.
